/** @type {import('tailwindcss').Config} */
module.exports = {
  presets: [require("nativewind/preset")],
  content: [
    "./src/app/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        appBg: "#06151e",
        primary: "#FFEE58",
        welcomebg: "#020b15",
        textlight: "#9B9B9B",
        inputbg: "#EFEFEF",
        darkinputbg: "#1f1f1f",
        inputborder: "#A2A2A299",
        buttonBg: "#0037E8",
        secondary: "#9A9A9A",
        boxBorder: "#e2e6ea",
        grayscale: "#1E1E1E",
        grayscale3: "#2F2F2F",
        grayscale6: "#6E6E6E",
        grayscale8: "#EEEEEE",
        grayscale7: "#B0B0B0",
        grayscale9: "#F0F0F0",
        darkBorder: "#2F2F2F",
        darkbg: "#1E1E1E",
        darkinputsbg: "#2B2B2B",
        grayborder: "#e6e6e6",
        border: "#a0a4a8",
        buttonlightbg: "#e1e5e9",
        primarytext: "#66686c",
      },
      fontFamily: {
        pthin: ["Poppins-Thin", "sans-serif"],
        pextralight: ["Poppins-ExtraLight", "sans-serif"],
        plight: ["Poppins-Light", "sans-serif"],
        pregular: ["Poppins-Regular", "sans-serif"],
        pmedium: ["Poppins-Medium", "sans-serif"],
        psemibold: ["Poppins-SemiBold", "sans-serif"],
        pbold: ["Poppins-Bold", "sans-serif"],
        pextrabold: ["Poppins-ExtraBold", "sans-serif"],
        pblack: ["Poppins-Black", "sans-serif"],
        aitalic: ["Avega-Italic", "sans-serif"],
        campana: ["CampanaScript"],
        curl: ["Writeline"],
        dsemibold: ["DancingScript-SemiBold", "sans-serif"],
        dbold: ["DancingScript-Bold", "sans-serif"],
      },
    },
  },
  plugins: [],
};
